// This exhibits an error in SmithWatFree, where a 

#include "MainTools.h"
#include "pairwise_aligners/SmithWatFree.h"
#include "PrintAlignment.h"

int main( int argc, char** argv )
{
  BeginCommandArguments;
  CommandArgument_String_OrDefault( SHORT,
    "TCCATGGCTGTCGAATCAATAAATGTGTAATTGTTAATGTACATGCTGGGCTGGTGGTTGTCAAAATGACTAACTGCTTC"
    "AATAGCATCCTTTCCAAACATTCTGTTTATGGTCTAATAACACCCAATCCAGACTGTTTCCCTGCACCAGAAACTATGTA"
    "GTGTAAGCTGGCAAACTCAGCTCTAGCAACAGCACAATATTCAGCCACCCTCAGCAAAAATGCCACAAGATAAGATTATT"
    "TTTTATAACATTACTGTTGTTACTGACACAAAATTGATACCTATTGAATTAGTATTTTCTTTACATTCCAAACTCTAAAA"
    "CACACTTTATAAATGTAGTACTCAAAACAGTATAAAAGAAGAGAAAGACAGATGAATGGTGCATGGAAGAAAGCCTTCCC"
    "CCCAACAGCAAAGCCAGTAAAACCAAGTCATGACAATGTTTTCAGCAAATGGTGAAAGAACAATGTACCCTGATACACAA"
    "AATGAGAGGAAATTAATTTATACCAAGACCTTCAATTTATTCCAAAAATTAGCTGAAAACAGAACATAGACATAAATGTA"
    "AAATTCAAATTACAGAACTCCTGAATGATGATGAACCAAAACAAGAGATTATTTTCTTTATTTTTCCTAAGTCCTCATCA"
    "CTGACTTTTGAATTGTTACCTACTTGGTTTTGAGGATTTCATACATGAAAATTGTGTTTATATCATGTATCACCCTCTTC"
    "CTTCCAATTCCTCTCAAATTCATGAGACTTCATTTTCTTTAATTTTTACACACACACACACACACACACACACACACACA"
    "CACACACATTTGTTTTCAATTAAAGAAAAAGGAAAATGGCACAGACTGCACTGTTTCTTACACAACATAACAAGTTTTCC"
    "ATGTCATCTAGCAGTATGCTTCTTGGTATATATCCAGATGATCTCAAAGTTTATCCATCAAATCTGAACAGAACATTTTA"
    "GTTAAAATTTTTATTCAAAAATATTTTTTACTTTGTTTATATGTTATTTCCTCTCTCTTTTATCCTTCTCCACTTCTTCC"
    "CATGTCTCTCTGACTCCCTCTTAATTTTATGATCTCTTCTTCTTTAATTATTATTGTTAAACATAAACACACCTTCTTGA"
    "CTTTATTACTGTAGTATGTTTATACATGTGCTTAGTGAGGACCACATGGGATGTGCGAACCTATTAGAGACTTGAGCTTG"
    "AATAGACAGCAGGAAATAATCAAACTCAGGGGTGAAATCAAACAAGTGGAAACAAGAAGAACTACTCAAAGAATCAACCA"
    "AATGAGGAGCTGGTTCTTTGAGAAAAATCAATAAGATAGATAAACCCTTAGCCAGACTCACTAGAGGGCACAGGGAAAGC"
    "ATCCTAATTAACAAAATCAGAAATGAAAAGGGAGACATAACAACAGATCCTGAAGAAATACAAAACACCATCAGATCCTT"
    "CTACAAAAGGCTATACTCAACAAAACTGGAGAACCTGGATAAAATGTACAAGTTTCTAGACAGATACCAGGTACCAAAGT"
    "TAAATAAAGATCAGGTTAATGATCTAAACAGTCTTATATCCCCTAAAGAAAGAGAAGCAGTAATTAATAATCTCCCAACC"
    "AAAAAAAGCCCAGGACCACATGGATTGAGTGCAGAGTTCTATCAGAACTTCAAAGAAGATCTAATCCCAGTTCTTCACAA"
    "ACTATTCCACAAAATAGAAGCAGAAGGCACTCTACCCAACTCATTCTATGAAGCCACAATTACTCTGATACCTAAACCAC"
    "AAAAAGACCCAACAAAGATAGAGAACTTCAGACCAATTTCCCTTATGAATATTGATGCAAAAATACTCAATAAAGTTCTC"
    "GCTAACCAAATCCAAGAACACATCAAAGCAAACATCCATCCTGACCAAGTAGGTTTCATCCCAGGGATTCAGGGATGGTT"
    "CAATATACTGAAATCCATCAATGTAATCCAGTATATAAACAAACTCAAGGACAAAAACCACATGATCATCTCATTAGATG"
    "CAGAGAAAGCATTGGACAAAATCCATCACCCATTCATGATAATAGTCTTGGAAAGATCAGGAATTAAAGGCCCATACATA"
    "AACATGATAAAAGCAATGTACAGCAAAAAAGTAGCCAACATCAAAGTAAATGGTGAGAAGCTGGAAGCAATCCCACTAAA"
    "ATCAGGGAATAGACAAGGCTGGCCACATTCTCCCTAGCTATTCAACATTGTACTTGAAGTCCTATCCAGAGCAATTCGAC"
    "AACAAAAGGAGATCAAGGGAATGCAAATTGGAAAGGAAGAAGTCAAAATATCACTTTTTTTGCAGATGATATGATAGTAT"
    "ATGTAAGTGACCCTAAAAATTCTACCAAAGACTCCTTAACCTGATAAACAGCTTCAATGAAGTAGCTGGATATAAAATTA"
    "ACTCAAAGAAATCAATGGCCTTTCTGTACACAAAGGATAAAAAAGTTGAGAAAGATATTAGGGAAACAACACCCTTCTCA"
    "ATAGTCACAAATAATATAAAATACCTTGGCCTGACTCTAAGTAAGGAAGTGAAAGATCTGTATGATAAGAGCTTCAAGTC"
    "TCTGAAGAAAGAAATTAAAGAAGATCTCAGAAGATGGAAAGATCTCCCATGCTCATGGATTGGCAGGATCGATATAGTAA"
    "AAATGGCTATCTTGTCAAAAGCAATCTACAGATTCAATGCAATCCCTATCAAAATTCCAACTCAATTCTTCAACAATTTA"
    "GAAAGGGCAATCTGCAAATTCATCTGGAATAACAAAAAACCTAGGATAGCAAAAACTCTGCTCAAGGATAAAAGAATGTC"
    "TGGTGGAATCACCATGCCTGACCTAAAGCTCTACTACAGAACAATTGTGATAAAAACTGCTTGGTACTGGTATAGAGAGA"
    "GACAAGTAGACCAATGGAATAGAATTGAAGACCCAGTAATGAACCCACACACCTATGGTCTCTGGATCTTTGACAAGGGA"
    "GCTAAAACCATTCAGTGGAAAAAAGACAGCATTTTCAACAAATGGTGCTGGCACAACTGGTGGTTATCATGTAGAAGAAT"
    "GCGAATTGATCCATTCCAATCTCCTTGTACTAAGGTCAAATCTAAGTAAACTAAAGAACTTCACATAAAACCAGAGACAC"
    "TGAAACATATAGAGGAGAAAGTAGGGAAAAGCCTTGAAGACATGGATACAGGGGAAAAATTCCTGAATAGAAGAGCAATG"
    "GCTTGTCCTGTAAGAAGGAACTCACACAATATGTACTCACTGATAAGTGGATATTAGCCCCAAACCTAGGATACCCAAGA"
    "TATAAGATACAATTTCCTAAACACATGAAACTCAAGAAAAATGAAGACTGAAGTGCGGACACTATGCCCCTCCTTAGAAG"
    "TGGGAACAAAACACCCATGGAAGGAGTTACAGAGAAAAAGTTTGGAGCTGAGATGAAAGGATGGAC" );

  CommandArgument_String_OrDefault( LONG,
    "ATGTAAAATTCAAATTACAGAACTCCTGAATGATGATGAACCAAAACAAGAGATTATTTTCTTTATTTTTCCTAAGTCCT"
    "CATCACTGACTTTTGAATTGTTACCTACTTGGTTTTGAGGATTTCATACATGAAAATTGTGTTTATATCATGTATCACCC"
    "TCTTCCTTCCAATTCCTCTCAAATTCATGAGACTTCATTTTCTTTAATTTTTACACACACACACACACACACACACACAC"
    "ACACACACACACATTTGTTTTCAATTAAAGAAAAAGGAAAATGGCACAGACTGACTGTTTCTTACACAACATAACAAGTT"
    "TTCCATGTCATCTAGCAGTATGCTTCTTGGTATATATCCAGATGATCTCAAAGTTTATCCATCAAATCTGAACAGAACAT"
    "TTTAGTTAAAATTTTTATTCAAAAATATTTTTTACTTTGTTTATATGTTATTTCCTCTCTCTTTTATCCTTCTCCACTTC"
    "TTCCCATGTCTCTCTGACTCCCTCTTAATTTTATGATCTCTTCTTCTTTAATTATTATTGTTAAACATAAACACACCTTC"
    "TTGACTTTATTACTGTAGTATGTTTATACATGTGCTTAGTGAGGACCACATGGGATGTGCGAACCTATTAGAGACTTGAG"
    "CTTGAATAGACAGCAGGAAATAATCAAACTCAGGGGTGAAATCAAACAAGTGGAAACAAGAAGAACTACTCAAAGAATCA"
    "ACCAAATGAGGAGCTGGTTCTTTGAGAAAAATCAATAAGATAGATAAACCCTTAGCCAGACTCACTAGAGGGCACAGGGA"
    "AAGCATCCTAATTAACAAAATCAGAAATGAAAAGGGAGACATAACAACAGATCCTGAAGAAATACAAAACACCATCAGAT"
    "CCTTCTACAAAAGGCTATACTCAACAAAACTGGAGAACCTGGATAAAATGTACAAGTTTCTAGACAGATACCAGGTACCA"
    "AAGTTAAATAAAGATCAGGTTAATGATCTAAACAGTCTTATATCCCCTAAAGAAAGAGAAGCAGTAATTAATAATCTCCC"
    "AACCAAAAAAAGCCCAGGACCACATGGATTGAGTGCAGAGTTCTATCAGAACTTCAAAGAAGATCTAATCCCAGTTCTTC"
    "ACAAACTATTCCACAAAATAGAAGCAGAAGGCACTCTACCCAACTCATTCTATGAAGCCACAATTACTCTGATACCTAAA"
    "CCACAAAAAGACCCAACAAAGATAGAGAACTTCAGACCAATTTCCCTTATGAATATTGATGCAAAAATACTCAATAAAGT"
    "TCTCGCTAACCAAATCCAAGAACACATCAAAGCAAACATCCATCCTGACCAAGTAGGTTTCATCCCAGGGATTCAGGGAT"
    "GGTTCAATATACTGAAATCCATCAATGTAATCCAGTATATAAACAAACTCAAGGACAAAAACCACATGATCATCTCATTA"
    "GATGCAGAGAAAGCATTGGACAAAATCCATCACCCATTCATGATAATAGTCTTGGAAAGATCAGGAATTAAAGGCCCATA"
    "CATAAACATGATAAAAGCAATGTACAGCAAAAAAGTAGCCAACATCAAAGTAAATGGTGAGAAGCTGGAAGCAATCCCAC"
    "TAAAATCAGGGAATAGACAAGGCTGGCCACATTCTCCCTAGCTATTCAACATTGTACTTGAAGTCCTATCCAGAGCAATT"
    "CGACAACAAAAGGAGATCAAGGGAATGCAAATTGGAAAGGAAGAAGTCAAAATATCACTTTTTTTGCAGATGATATGATA"
    "GTATATGTAAGTGACCCTAAAAATTCTACCAAAGACTCCTTAACCTGATAAACAGCTTCAATGAAGTAGCTGGATATAAA"
    "ATTAACTCAAAGAAATCAATGGCCTTTCTGTACACAAAGGATAAAAAAGTTGAGAAAGATATTAGGGAAACAACACCCTT"
    "CTCAATAGTCACAAATAATATAAAATACCTTGGCCTGACTCTAAGTAAGGAAGTGAAAGATCTGTATGATAAGAGCTTCA"
    "AGTCTCTGAAGAAAGAAATTAAAGAAGATCTCAGAAGATGGAAAGATCTCCCATGCTCATGGATTGGCAGGATCGATATA"
    "GTAAAAATGGCTATCTTGTCAAAAGCAATCTACAGATTCAATGCAATCCCTATCAAAATTCCAACTCAATTCTTCAACAA"
    "TTTAGAAAGGGTAATCTGCAAATTCATCTGGAATAACAAAAAACCTAGGATAGCAAAAACTCTGCTCAAGGATAAAAGAA"
    "TGTCTGGTGGAATCACCATGCCTGACCTAAAGCTCTACTACAGAACAATTGTGATAAAAACTGCTTGGTACTGGTATAGA"
    "GAGAGACAAGTAGACCAATGGAATAGAATTGAAGACCCAGTAATGAACCCACACACCTATGGTCTCTGGATCTTTGACAA"
    "GGGAGCTAAAACCATTCAGTGGAAAAAAGACAGCATTTTCAACAAATGGTGCTGGCACAACTGGTGGTTATCATGTAGAA"
    "GAATGCGAATTGATCCATTCCAATCTCCTTGTACTAAGGTCAAATCTAAGTAAACTAAAGAACTTCACATAAAACCAGAG"
    "ACACTGAAACATATAGAGGAGAAAGTAGGGAAAAGCCTTGAAGACATGGATACAGGGGAAAAATTCCTGAATAGAAGAGC"
    "AATGGCTTGTCCTGTAAGAAGGAACTCACACAATATGTACTCACTGATAAGTGGATATTAGCCCCAAACCTAGGATACCC"
    "AAGATATAAGATACAATTTCCTAAACACATGAAACTCAAGAAAAATGAAGACTGAAGTGCGGACACTATGCCCCTCCTTA"
    "GAAGTGGGAACAAAACACCCATGGAAGGAGTTACAGAGAAAAAGTTTGGAGCTGAGATGAAAGGATGGACAATGTAGAGA"
    "CTGCCATATCCAGGGATCCACCCCATAATCAGCATCCAAACGCTGACACCATTGCATACACTAGCAAGATTTTATCGAAA"
    "GGACCCAGATGTAGCTGTCTCTTGTGAGACTATGCCGGGGCCTAGCAAACACAGAAGTGGATGCTCACAGTCAGCTAATG"
    "GATGGATCACAGGGCTCCCAATGGAGGAGCTAGAGAATGTACCCAAGGAGCTAAAGGGATCTGCAACCCTATAGGTGGAA"
    "CAACATTATGAACTAACCAGTACCCCGGAGCTCTTGACTCTAGCTGCATATGTATCAAAAGATGGCCTAGTCGGCCATCA"
    "CTGGAAAGAGAGGCCCATTGGACACACAAACTTTATATGCCGCAGTACAGGGGAACGCCAGGGCCAAAAAGGGGGAGTGG"
    "GTGGGTAGGGGAGTGGGGGTGGGTGGGTATGGGGGACTTTTGGTATAGCATTGGAAATGTAAATGAGCTAAATACCTAAT"
    "AAAAAATGGAAAAAAAAAGAATCGACAAATTGGACCTCATAAATTTGCAAAGCTTCTGCAAGGCAAAAGGATGGAC" );
   
  CommandArgument_Bool_OrDefault( PENALIZE_LEFT, False );
  CommandArgument_Bool_OrDefault( PENALIZE_RIGHT, False );
  EndCommandArguments;

  basevector seq1;
  basevector seq2;

  PRINT( SHORT.size() );
  PRINT( LONG.size() );

  seq1.Setsize( SHORT.size() );
  seq2.Setsize( LONG.size() );

  seq1.SetFromString( SHORT );
  seq2.SetFromString( LONG );

  alignment a;

  int best_offset;

  float score = SmithWatFree( seq1, seq2, best_offset, a, PENALIZE_LEFT, PENALIZE_RIGHT );
  
  int pos1(0), pos2(0), errors(0);
  avector<int> gaps(0), lengths(0);

  PrintVisualAlignment( False, cout, seq1, seq2, a );
}
  
