/////////////////////////////////////////////////////////////////////////////
//                   SOFTWARE COPYRIGHT NOTICE AGREEMENT                   //
//       This software and its documentation are copyright (2007) by the   //
//   Broad Institute/Massachusetts Institute of Technology.  All rights    //
//   are reserved.  This software is supplied without any warranty or      //
//   guaranteed support whatsoever. Neither the Broad Institute nor MIT    //
//   can be responsible for its use, misuse, or functionality.             //
/////////////////////////////////////////////////////////////////////////////

#include "Basevector.h"
#include "MainTools.h"
#include "random/Random.h"

int main( int argc, char** argv ) {
  RunTime();

  String seq(
    "TCCATGGCTGTCGAATCAATAAATGTGTAATTGTTAATGTACATGCTGGGCTGGTGGTTGTCAAAATGACTAACTGCTTC"
    "AATAGCATCCTTTCCAAACATTCTGTTTATGGTCTAATAACACCCAATCCAGACTGTTTCCCTGCACCAGAAACTATGTA"
    "GTGTAAGCTGGCAAACTCAGCTCTAGCAACAGCACAATATTCAGCCACCCTCAGCAAAAATGCCACAAGATAAGATTATT"
    "TTTTATAACATTACTGTTGTTACTGACACAAAATTGATACCTATTGAATTAGTATTTTCTTTACATTCCAAACTCTAAAA"
    "CACACTTTATAAATGTAGTACTCAAAACAGTATAAAAGAAGAGAAAGACAGATGAATGGTGCATGGAAGAAAGCCTTCCC"
    "CCCAACAGCAAAGCCAGTAAAACCAAGTCATGACAATGTTTTCAGCAAATGGTGAAAGAACAATGTACCCTGATACACAA"
    "AATGAGAGGAAATTAATTTATACCAAGACCTTCAATTTATTCCAAAAATTAGCTGAAAACAGAACATAGACATAAATGTA"
    "AAATTCAAATTACAGAACTCCTGAATGATGATGAACCAAAACAAGAGATTATTTTCTTTATTTTTCCTAAGTCCTCATCA"
    "CTGACTTTTGAATTGTTACCTACTTGGTTTTGAGGATTTCATACATGAAAATTGTGTTTATATCATGTATCACCCTCTTC"
    "CTTCCAATTCCTCTCAAATTCATGAGACTTCATTTTCTTTAATTTTTACACACACACACACACACACACACACACACACA"
    "CACACACATTTGTTTTCAATTAAAGAAAAAGGAAAATGGCACAGACTGCACTGTTTCTTACACAACATAACAAGTTTTCC"
    "ATGTCATCTAGCAGTATGCTTCTTGGTATATATCCAGATGATCTCAAAGTTTATCCATCAAATCTGAACAGAACATTTTA"
    "GTTAAAATTTTTATTCAAAAATATTTTTTACTTTGTTTATATGTTATTTCCTCTCTCTTTTATCCTTCTCCACTTCTTCC"
    "CATGTCTCTCTGACTCCCTCTTAATTTTATGATCTCTTCTTCTTTAATTATTATTGTTAAACATAAACACACCTTCTTGA"
    "CTTTATTACTGTAGTATGTTTATACATGTGCTTAGTGAGGACCACATGGGATGTGCGAACCTATTAGAGACTTGAGCTTG"
    "AATAGACAGCAGGAAATAATCAAACTCAGGGGTGAAATCAAACAAGTGGAAACAAGAAGAACTACTCAAAGAATCAACCA"
    "AATGAGGAGCTGGTTCTTTGAGAAAAATCAATAAGATAGATAAACCCTTAGCCAGACTCACTAGAGGGCACAGGGAAAGC"
    "ATCCTAATTAACAAAATCAGAAATGAAAAGGGAGACATAACAACAGATCCTGAAGAAATACAAAACACCATCAGATCCTT"
    "CTACAAAAGGCTATACTCAACAAAACTGGAGAACCTGGATAAAATGTACAAGTTTCTAGACAGATACCAGGTACCAAAGT"
    "TAAATAAAGATCAGGTTAATGATCTAAACAGTCTTATATCCCCTAAAGAAAGAGAAGCAGTAATTAATAATCTCCCAACC"
    "AAAAAAAGCCCAGGACCACATGGATTGAGTGCAGAGTTCTATCAGAACTTCAAAGAAGATCTAATCCCAGTTCTTCACAA"
    "ACTATTCCACAAAATAGAAGCAGAAGGCACTCTACCCAACTCATTCTATGAAGCCACAATTACTCTGATACCTAAACCAC"
    "AAAAAGACCCAACAAAGATAGAGAACTTCAGACCAATTTCCCTTATGAATATTGATGCAAAAATACTCAATAAAGTTCTC"
    "GCTAACCAAATCCAAGAACACATCAAAGCAAACATCCATCCTGACCAAGTAGGTTTCATCCCAGGGATTCAGGGATGGTT"
    "CAATATACTGAAATCCATCAATGTAATCCAGTATATAAACAAACTCAAGGACAAAAACCACATGATCATCTCATTAGATG"
    "CAGAGAAAGCATTGGACAAAATCCATCACCCATTCATGATAATAGTCTTGGAAAGATCAGGAATTAAAGGCCCATACATA"
    "AACATGATAAAAGCAATGTACAGCAAAAAAGTAGCCAACATCAAAGTAAATGGTGAGAAGCTGGAAGCAATCCCACTAAA"
    "ATCAGGGAATAGACAAGGCTGGCCACATTCTCCCTAGCTATTCAACATTGTACTTGAAGTCCTATCCAGAGCAATTCGAC"
    "AACAAAAGGAGATCAAGGGAATGCAAATTGGAAAGGAAGAAGTCAAAATATCACTTTTTTTGCAGATGATATGATAGTAT"
    "ATGTAAGTGACCCTAAAAATTCTACCAAAGACTCCTTAACCTGATAAACAGCTTCAATGAAGTAGCTGGATATAAAATTA"
    "ACTCAAAGAAATCAATGGCCTTTCTGTACACAAAGGATAAAAAAGTTGAGAAAGATATTAGGGAAACAACACCCTTCTCA"
    "ATAGTCACAAATAATATAAAATACCTTGGCCTGACTCTAAGTAAGGAAGTGAAAGATCTGTATGATAAGAGCTTCAAGTC"
    "TCTGAAGAAAGAAATTAAAGAAGATCTCAGAAGATGGAAAGATCTCCCATGCTCATGGATTGGCAGGATCGATATAGTAA"
    "AAATGGCTATCTTGTCAAAAGCAATCTACAGATTCAATGCAATCCCTATCAAAATTCCAACTCAATTCTTCAACAATTTA"
    "GAAAGGGCAATCTGCAAATTCATCTGGAATAACAAAAAACCTAGGATAGCAAAAACTCTGCTCAAGGATAAAAGAATGTC"
    "TGGTGGAATCACCATGCCTGACCTAAAGCTCTACTACAGAACAATTGTGATAAAAACTGCTTGGTACTGGTATAGAGAGA"
    "GACAAGTAGACCAATGGAATAGAATTGAAGACCCAGTAATGAACCCACACACCTATGGTCTCTGGATCTTTGACAAGGGA"
    "GCTAAAACCATTCAGTGGAAAAAAGACAGCATTTTCAACAAATGGTGCTGGCACAACTGGTGGTTATCATGTAGAAGAAT"
    "GCGAATTGATCCATTCCAATCTCCTTGTACTAAGGTCAAATCTAAGTAAACTAAAGAACTTCACATAAAACCAGAGACAC"
    "TGAAACATATAGAGGAGAAAGTAGGGAAAAGCCTTGAAGACATGGATACAGGGGAAAAATTCCTGAATAGAAGAGCAATG"
    "GCTTGTCCTGTAAGAAGGAACTCACACAATATGTACTCACTGATAAGTGGATATTAGCCCCAAACCTAGGATACCCAAGA"
    "TATAAGATACAATTTCCTAAACACATGAAACTCAAGAAAAATGAAGACTGAAGTGCGGACACTATGCCCCTCCTTAGAAG"
    "TGGGAACAAAACACCCATGGAAGGAGTTACAGAGAAAAAGTTTGGAGCTGAGATGAAAGGATGGAC" );

  basevector bv;
  bv.SetFromString( seq );

  for ( unsigned int i = 0; i < 100000; ++i ) {
    int begin = randomx() % bv.size();
    int end = randomx() % bv.size();
    if ( end < begin )
      swap( begin, end );

    int gcOld = 0;
    for ( int j = begin; j < end; ++j )
      if ( IsGC(bv[j]) )
        ++gcOld;

    int gcNew = bv.GcBases( begin, end );

    if ( gcNew != gcOld ) {
      PRINT2( gcOld, gcNew );
      String sub = seq.substr( begin, end - begin );
      cout << sub << endl;
    }
  }
}
