// Copyright (c) 2000-2003 Whitehead Institute for Biomedical Research
// 

#ifndef PRIMATE_CONTIG_LOG_PARSER_H
#define PRIMATE_CONTIG_LOG_PARSER_H

#include "String.h"



/*
 * class pclog_parser
 *
 * It parses log files generated by primate_contig (tiled contigs).
 */
class pclog_parser {
  
public:

  pclog_parser( );
  
  pclog_parser( int chr_id, int contig_id, int n_reads, int begin, int len );

  void Set( int chr_id, int contig_id, int n_reads, int begin, int len );
  
  int ChrId( ) const { return chr_id_; }

  int ContigId( ) const { return contig_id_; }

  int ReadsCount( ) const { return n_reads_; }

  int Begin( ) const { return begin_; }

  int Length( ) const { return len_; }

  int End( ) const { return ( begin_ + len_); }
  
  friend istream &operator>> ( istream &in, pclog_parser &pclog );
  
  friend ostream &operator<< ( ostream &out, const pclog_parser &pclog );
  
  
private:
  
  int chr_id_;
  int contig_id_;
  int n_reads_;
  int begin_;
  int len_;
  
};



#endif
